### PR TITLE
Feature: Exempt labels from action

### LINKED ISSUE #10: Exempt specific labels from action?
For instance, we'd like to exclude issues labeled `help wanted` from the auto-closer, because we'd like contributors to pick these up down the line.

### PR DESCRIPTION
**Pull request by ryanwilsonperkin**
Fixes #10 

Hey! This is the first action that we've tried out on our repos and it seems great. I'm an engineer on our Developer Systems team at Wave and we support features like this to help developers get their work done.

We had an internal request for this feature, and then I saw that it was already listed as an issue so I decided to take a crack at it. Thanks to @vincentschen, @christopheranderson, and @damccorm for the discussion that's happened so far on #10.

I'm not sure how best to test a change like this, and I'm open to any advice from the maintainers/owners of this project. Thanks

### CODE REVIEW

**Comment by NARKOZ** [comment]
Is it possible to set several exempt labels?

**Comment by ryanwilsonperkin** [comment]
@NARKOZ no

**Comment by skjnldsv** [comment]
>> Is it possible to set several exempt labels?
>
> @NARKOZ no


created issue https://github.com/actions/stale/issues/17 :)

**Comment by nchammas** [comment]
@damccorm 

> Published! Both `actions/stale@v1` and `actions/stale@v1.1.0` should have this

The [latest version](https://github.com/marketplace/actions/close-stale-issues) shows as 1.0.0. Is 1.1.0 somehow not fully released yet?

**Comment by damccorm** [comment]
@bryanmacfarlane to take a look - the tag is definitely valid - https://github.com/actions/stale/releases, but it isn't showing up that way in the marketplace

**Pull request merged**
