### PR TITLE
chore(logs): enhance the logs

### LINKED ISSUE #361: Refactor the operations left to make it a class

### PR DESCRIPTION
**Pull request by C0ZEN**
**Changes:**
- [x] Add logs for the milestones options
- [x] Use `core.setFailed` instead of throwing errors https://github.com/actions/toolkit/tree/main/packages/core#exit-codes
- [x] Tackle the current issues processor logs (partially as a first draft)
- [x] Beautiful logs (partially as a first draft)

Partial of #347 
Closes #361

### CODE REVIEW

**Comment by C0ZEN** [comment]
@hross hello.
This PR is very opinionated regarding the logs due to including colored ones.
I wish to know if it's ok with you or if you want to change something or if you want to drop the color.
I wait your feedback before continuing.

Example

**Review by hross — APPROVED** [review]

**Comment by hross** [comment]
I love the colors! let me know if you want me to merge now or wait

**Comment by C0ZEN** [comment]
@hross 😎 yes you can merge it so I will be able to see if it is working through the octokit logs. I will provide a second PR soon

**Comment by hross** [comment]
will let this sit in master until the end of the week and release it.

**Pull request merged**
