### PR TITLE
feat(any-of-labels): add 2 new options to customize for issues/PRs

### LINKED ISSUE #371: Allow to change any-of-labels for issues and PRs.
Like `only-labels` does.

See https://github.com/actions/stale/issues/370

### PR DESCRIPTION
**Pull request by C0ZEN**
**Changes:**
- [x] Add new options to override the `any-of-labels` option for issues and PRs
- [x] Enhance the logs for `any-of-labels` and `only-labels` to display as a tree 

Closes #371

### CODE REVIEW

**Comment by C0ZEN** [comment]
@hross ready as well

**Comment by C0ZEN** [comment]
@joeveiga touching one of your contribution. FYI I changed more content in the specs to reflect the ones for `only-labels`. A mix between your syntax and mine so maybe you like it, maybe not. Feel free to suggest.

**Comment by joeveiga** [comment]
@C0ZEN LGTM! Yeah the idea of the SUT builder is exactly that, to be as expressive as possible in the test case. Nice 👍

**Comment by pllim** [comment]
Hello. What is the timeline of this going in? Just wondering. Thanks!

**Review by luketomlinson — APPROVED** [review]
This LGTM @C0ZEN 💰 Makes it consistent with `only-labels`

**Comment by C0ZEN** [comment]
@pllim dunno but usually GitHub keep the stale bot internal for a week before creating a release to make sure it works as expected.
If you truly want to opt-in you can use the main branch when configuring which version to use in your workflow but it's not the best practice.

**Comment by pllim** [comment]
Gotcha. I'll keep an eye out for the release. Thanks for the heads up!

**Pull request merged**
