### PR TITLE
Fix spaces in `issues-processor.ts`

### PR DESCRIPTION
**Pull request by Saibamen**
## Changes

- Fix spaces in `issues-processor.ts`

## Context

image

### CODE REVIEW

**Review by luketomlinson — APPROVED** [review]

**Comment by luketomlinson** [comment]
@Saibamen You'll need to run `npm run pack` and commit the result too.

**Comment by Saibamen** [comment]
> @Saibamen You'll need to run `npm run pack` and commit the result too.

@luketomlinson:

After `npm install`:
```
added 973 packages, and audited 974 packages in 28s

98 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

After `npm run pack`:

```
> stale-action@2.0.0 pack
> ncc build

Error: Cannot find module 'C:\Users\Adam\source\repos\stale\lib\main.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:353:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:566:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at resolve (node:internal/modules/cjs/helpers:108:19)
    at runCmd (C:\Users\Adam\source\repos\stale\node_modules\@vercel\ncc\dist\ncc/cli.js.cache.js:1:51752)
    at Object.819 (C:\Users\Adam\source\repos\stale\node_modules\@vercel\ncc\dist\ncc/cli.js.cache.js:1:48659)
    at __webpack_require__ (C:\Users\Adam\source\repos\stale\node_modules\@vercel\ncc\dist\ncc/cli.js.cache.js:1:55378)
    at C:\Users\Adam\source\repos\stale\node_modules\@vercel\ncc\dist\ncc/cli.js.cache.js:1:55590
    at C:\Users\Adam\source\repos\stale\node_modules\@vercel\ncc\dist\ncc/cli.js.cache.js:1:55651
    at Object.<anonymous> (C:\Users\Adam\source\repos\stale\node_modules\@vercel\ncc\dist\ncc\cli.js:8:28) {
  code: 'MODULE_NOT_FOUND',
  path: 'C:\\Users\\Adam\\source\\repos\\stale\\package.json',
  requestPath: 'C:\\Users\\Adam\\source\\repos\\stale'
}
```

NPM version: `8.10.0`
Node version: `v16.15.0`

**Comment by luketomlinson** [comment]
@Saibamen does running `nom run build` first fix it? I forgot that needs to be run first 🤦‍♂️

**Comment by Saibamen** [comment]
@luketomlinson: fixed, thanks

**Pull request merged**
