### PR TITLE
Add support for posting comment on closure

### PR DESCRIPTION
**Pull request by owenvoke**
This (hopefully) adds support for posting a comment when closing the issue/pr due to it being stale.

By default it won't post a closure comment, this is the equivalent of the [`closeComment`](https://github.com/tldr-pages/tldr/blob/208327d21a7373591f5024bf52dd1cb9ddee17f2/.github/stale.yml#L21-L26) config in [Stale Bot](https://github.com/probot/stale). However, it can be different for issues and PRs.

### CODE REVIEW

**Comment by sbrl** [comment]
Very cool!

I see that the close / stale messages are configurable. I assume there's a config file somewhere that we'll have to create or something for this?

**Comment by owenvoke** [comment]
@sbrl, yeah, for tldr pages we will need to update the workflow that I've added in https://github.com/tldr-pages/tldr/pull/4143. 👍

**Comment by zdroid** [comment]
:+1: This is a very useful feature, since it adds the missing functionality from StaleBot.

**Comment by MikeyMJCO** [comment]
What's blocking merge on this?

**Comment by sbrl** [comment]
I don't think we've had a single comment from someone with merge privileges yet @MikeyMJCO :confused:

**Comment by sbrl** [comment]
This is perhaps a bit rude, but /cc @andymckay, @hross, @fjeremic, and @pjquirk (4 of the most recent committers)

**Comment by hross** [comment]
Seems like a good changes. I've merged it to master. You can test it with @master. I'll bump the version later this week for the main action.

**Comment by owenvoke** [comment]
Thank you, @hross.

**Pull request merged**
