### PR TITLE
draft release for v7.0.0

### PR DESCRIPTION
**Pull request by johnsudol**
## Changes

- [x] Update change log for v7

## Context
#874 introduced a breaking change for exempt items. We are releasing a major version (v7) to not break existing versions.

### CODE REVIEW

**Review by vanZeben — APPROVED** [review]
Thanks for updating the version in the package files :)

**Comment by olabskid** [comment]
511

**Comment by olabskid** [comment]
> 511

**Comment by harshu1234567** [comment]
name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v6
        with:
          stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days.'
          days-before-stale: 30
          days-before-close: 5

**Pull request merged**
