### PR TITLE
feat(milestones): add new options to exempt all milestones

### LINKED ISSUE #283: Avoid stale for all milestones
Add new option `exempt-all-milestones`.

See original idea from here https://github.com/actions/stale/issues/270.

### PR DESCRIPTION
**Pull request by C0ZEN**
**Note**: 
It was created from #290 so it would be better to merge it first.
It would be cooler if #289 can be merged before too so that the beta or alpha release can be tested.

**Changes:**
- [x] Create more spec files to test the general behaviour of the stale action
- [x] Move into their own files the utils code to test the general behaviour of the stale action
- [x] Refactor the tests for the milestones
	- Add coverage for issues AND pull requests as it should
	- Create a more nested structure to be more logical and make sure no cases was forgotten
	- Note: damn this is a 10k rows kind of spec file... since there is now 6 options playing altogether with the milestones there is a bunch of possible config combinations and I am pretty sure to cover them all at this cost. Any suggestion is welcome
- [x] Create a tsconfig for the spec and for the app to make sure eslint AND jest find the right files at any moment
- [x] Rename the pr wordings to make it more consistent and more user-friendly
- [x] Add new options to ignore all issues and PRs with milestones with their respective sub-options to do that only for issues OR pull requests - the option has a better priority than the current exempt milestones options

Closes #283

### CODE REVIEW

**Comment by C0ZEN** [comment]
With this refactor it reduces the spec LOC from 10k to 3.4k.
I still think that this is possible to improve it even more to have at the end a single matrix.

**Review by hross — APPROVED** [review]

**Comment by hross** [comment]
@C0ZEN this one is going to need a rebase to merge

**Comment by C0ZEN** [comment]
@hross hello and thank you for the feedbacks. I rebased this one and reviewed it, seems ready to go IMO.

**Comment by C0ZEN** [comment]
Thanks!

**Pull request merged**
